# Generated by Django 5.2.4 on 2025-07-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='adharcard_no',
            field=models.CharField(default=123354, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fees',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='trade',
            field=models.CharField(choices=[('Electrician', 'Electrician'), ('Fitter', 'Fitter')], max_length=20),
        ),
    ]
