# Generated by Django 5.2.4 on 2025-07-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_student_adharcard_no_alter_fees_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='fees_receipt_no',
            field=models.CharField(default=11, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
