# Generated by Django 5.2.4 on 2025-07-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_historicalfees'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(default='sonal', max_length=100),
            preserve_default=False,
        ),
    ]
