# Generated by Django 5.2.4 on 2025-07-03 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_alter_fees_options_alter_historicalfees_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentfees', to='fees.student'),
        ),
    ]
