# Generated by Django 5.2.4 on 2025-07-03 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_alter_fees_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.student'),
        ),
    ]
