# Generated by Django 5.2.4 on 2025-07-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_alter_fees_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historicalfees',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_fees',
            field=models.IntegerField(),
        ),
    ]
